### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/export/jw/cnn/insuranceQA/train'

### ISSUE THREAD

**Issue by ghost** [white127/insuranceQA-cnn-lstm#17]
where do i get this file?

**Comment by ghost** [comment]
**# I changed all the absolute path to project path "../../insuranceQA/"，and change the file name "insuranceQA/test1" to "insuranceQA/test1.sample"，after running cnn/tensorflow/insqa_train.py, I got following error message:**
input_x_1  Tensor("input_x_1:0", shape=(100, 200), dtype=int32, device=/device:GPU:1)
Traceback (most recent call last):
  File "insqa_train.py", line 76, in <module>
    l2_reg_lambda=FLAGS.l2_reg_lambda)
  File "/Users/timothy/Documents/sample/insuranceQA-cnn-lstm/cnn/tensorflow/insqa_cnn.py", line 100, in __init__
    pooled_reshape_1 = tf.reshape(tf.concat(3, pooled_outputs_1), [-1, num_filters_total]) 
  File "/Users/timothy/anaconda/envs/tensorflow2/lib/python3.4/site-packages/tensorflow/python/ops/array_ops.py", line 1043, in concat
    dtype=dtypes.int32).get_shape(
  File "/Users/timothy/anaconda/envs/tensorflow2/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/Users/timothy/anaconda/envs/tensorflow2/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/timothy/anaconda/envs/tensorflow2/lib/python3.4/site-packages/tensorflow/python/framework/constant_op.py", line 113, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/timothy/anaconda/envs/tensorflow2/lib/python3.4/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/timothy/anaconda/envs/tensorflow2/lib/python3.4/site-packages/tensorflow/python/framework/tensor_util.py", line 374, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Users/timothy/anaconda/envs/tensorflow2/lib/python3.4/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.
