### ISSUE TITLE
TypeError: ('An update must have the same type as the original shared variable 

### ISSUE THREAD

**Issue by ghost** [white127/insuranceQA-cnn-lstm#18]
python insqa_lstm.py
insqa_lstm.py:279: UserWarning: DEPRECATION: the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'.
  pooled_out = pool.pool_2d(input=conv_out, ds=(sequence_len - filter_size + 1, 1), ignore_border=True, mode='max')
Traceback (most recent call last):
  File "insqa_lstm.py", line 428, in <module>
    train()
  File "insqa_lstm.py", line 399, in train
    x1: p1, x2: p2, x3: p3, m1: q1, m2: q2, m3: q3
  File "/Users/timothy/anaconda/envs/tensorflow/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/Users/timothy/anaconda/envs/tensorflow/lib/python2.7/site-packages/theano/compile/pfunc.py", line 449, in pfunc
    no_default_updates=no_default_updates)
  File "/Users/timothy/anaconda/envs/tensorflow/lib/python2.7/site-packages/theano/compile/pfunc.py", line 208, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{sub,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

**Comment by chenyumiyu** [comment]
theano.config.floatX= 'float32' under import theano.
