### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'input_shape'

### ISSUE THREAD

**Issue by SeekPoint** [white127/insuranceQA-cnn-lstm#6]
rzai@rzai00:~/prj/insuranceQA-cnn-lstm/lstm_cnn/theano$ python insqa_lstm.py 
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled)
Traceback (most recent call last):
  File "insqa_lstm.py", line 433, in <module>
    train()
  File "insqa_lstm.py", line 387, in train
    num_filters=num_filters)
  File "insqa_lstm.py", line 259, in __init__
    cnn1 = self._cnn_net(tparams, cnn_input1, batch_size, sequence_len, num_filters, filter_sizes, proj_size)
  File "insqa_lstm.py", line 283, in _cnn_net
    conv_out = conv2d(input=cnn_input, filters=W, filter_shape=filter_shape, input_shape=image_shape)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/nnet/conv.py", line 149, in conv2d
    imshp=imshp, kshp=kshp, nkern=nkern, bsize=bsize, **kargs)
TypeError: __init__() got an unexpected keyword argument 'input_shape'
rzai@rzai00:~/prj/insuranceQA-cnn-lstm/lstm_cnn/theano$

**Comment by SeekPoint** [comment]
also see it on cnn:

rzai@rzai00:~/prj/insuranceQA-cnn-lstm/cnn/theano$ python insqa_cnn.py 
Using gpu device 0: GeForce GTX 1080 (CNMeM is disabled)
Traceback (most recent call last):
  File "insqa_cnn.py", line 313, in <module>
    train()
  File "insqa_cnn.py", line 263, in train
    num_filters=num_filters)
  File "insqa_cnn.py", line 180, in **init**
    conv_out = conv2d(input=input_x1, filters=W, filter_shape=filter_shape, input_shape=image_shape)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/nnet/conv.py", line 149, in conv2d
    imshp=imshp, kshp=kshp, nkern=nkern, bsize=bsize, **kargs)
TypeError: **init**() got an unexpected keyword argument 'input_shape'
rzai@rzai00:~/prj/insuranceQA-cnn-lstm/cnn/theano$
